### ISSUE TITLE
软件无法进入设置界面

### ISSUE THREAD

**Issue by Mirrorgo** [xianyukang/MyKeymap#8]
![image](https://user-images.githubusercontent.com/55936306/140610987-81b46661-2923-4f42-9af9-4411b5dbb861.png)

**Comment by xianyukang** [comment]
执行一下 bin\mykeymap-settings-server\mykeymap-settings-server.exe,  看看有什么报错

**Comment by Mirrorgo** [comment]
> 执行一下 bin\mykeymap-settings-server\mykeymap-settings-server.exe, 看看有什么报错

弹出了一下窗口，然后就马上自动关闭了，什么也没看到

**Comment by xianyukang** [comment]
> > 执行一下 bin\mykeymap-settings-server\mykeymap-settings-server.exe, 看看有什么报错
> 
> 弹出了一下窗口，然后就马上自动关闭了，什么也没看到

1. Alt + D 激活地址栏并输入 cmd 并回车
2. 用命令行执行 mykeymap-settings-server.exe 就能看到错误了

**Comment by Mirrorgo** [comment]
> > > 执行一下 bin\mykeymap-settings-server\mykeymap-settings-server.exe, 看看有什么报错
> > 
> > 
> > 弹出了一下窗口，然后就马上自动关闭了，什么也没看到
> 
> 1. Alt + D 激活地址栏并输入 cmd 并回车
> 2. 用命令行执行 mykeymap-settings-server.exe 就能看到错误了

![image](https://user-images.githubusercontent.com/55936306/140611656-02de7a8d-1151-48bc-8d74-61d75d7c5418.png)


Terminal只闪了一下就自动关闭了，所以我用screen to gif 在里面找到一帧有字的截出来了，就是有点糊😂

**Comment by Mirrorgo** [comment]
![test](https://user-images.githubusercontent.com/55936306/140611765-d21bc93d-d193-4287-a92e-321013c54598.gif)

**Comment by tmzncty** [comment]
我也遇到了这个问题。
Edition	Windows 11 Pro Insider Preview
Version	Dev
Installed on	‎29/‎10/‎2021
OS build	22489.1000
Experience	Windows Feature Experience Pack 1000.22489.1000.0
![图片](https://user-images.githubusercontent.com/72063145/140611830-594667ef-3fa8-47ff-ae6b-a21b0cc3d55f.png)
执行服务后也闪退。

**Comment by xianyukang** [comment]
> 我也遇到了这个问题。 Edition Windows 11 Pro Insider Preview Version Dev Installed on ‎29/‎10/‎2021 OS build 22489.1000 Experience Windows Feature Experience Pack 1000.22489.1000.0 ![图片](https://user-images.githubusercontent.com/72063145/140611830-594667ef-3fa8-47ff-ae6b-a21b0cc3d55f.png) 执行服务后也闪退。

这个问题好解决,  路径写错了,  等会修复

**Comment by tmzncty** [comment]
手动打开http://localhost:12333&nbsp; 解决问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xianyukang/MyKeymap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月6日(星期六) 晚上9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xianyukang/MyKeymap] 软件无法进入设置界面 (Issue #8)





  
我也遇到了这个问题。 Edition Windows 11 Pro Insider Preview Version Dev Installed on ‎29/‎10/‎2021 OS build 22489.1000 Experience Windows Feature Experience Pack 1000.22489.1000.0  执行服务后也闪退。
  
这个问题好解决,  路径写错了,  等会修复
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xianyukang** [comment]
> > > > 执行一下 bin\mykeymap-settings-server\mykeymap-settings-server.exe, 看看有什么报错
> > > 
> > > 
> > > 弹出了一下窗口，然后就马上自动关闭了，什么也没看到
> > 
> > 
> > 
> > 1. Alt + D 激活地址栏并输入 cmd 并回车
> > 2. 用命令行执行 mykeymap-settings-server.exe 就能看到错误了
> 
> ![image](https://user-images.githubusercontent.com/55936306/140611656-02de7a8d-1151-48bc-8d74-61d75d7c5418.png)
> 
> Terminal只闪了一下就自动关闭了，所以我用screen to gif 在里面找到一帧有字的截出来了，就是有点糊😂

我怀疑是 12333 端口被其他程序占用了,  你可以执行按下述步骤排查:
1. Alt + D 激活地址栏并输入 powershell 并回车
2. 执行 Get-Process -Id (Get-NetTCPConnection -LocalPort 12333).OwningProcess

**Comment by tmzncty** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xianyukang/MyKeymap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月6日(星期六) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xianyukang/MyKeymap] 软件无法进入设置界面 (Issue #8)





     
执行一下 bin\mykeymap-settings-server\mykeymap-settings-server.exe, 看看有什么报错
  
弹出了一下窗口，然后就马上自动关闭了，什么也没看到
   
Alt + D 激活地址栏并输入 cmd 并回车
 
用命令行执行 mykeymap-settings-server.exe 就能看到错误了
   

 
Terminal只闪了一下就自动关闭了，所以我用screen to gif 在里面找到一帧有字的截出来了，就是有点糊😂
  
我怀疑是 12333 端口被其他程序占用了,  你可以执行按下述步骤排查:
  
Alt + D 激活地址栏并输入 powershell 并回车
 
执行 Get-Process -Id (Get-NetTCPConnection -LocalPort 12333).OwningProcess
  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tmzncty** [comment]
如图所示。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xianyukang/MyKeymap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月6日(星期六) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xianyukang/MyKeymap] 软件无法进入设置界面 (Issue #8)





     
执行一下 bin\mykeymap-settings-server\mykeymap-settings-server.exe, 看看有什么报错
  
弹出了一下窗口，然后就马上自动关闭了，什么也没看到
   
Alt + D 激活地址栏并输入 cmd 并回车
 
用命令行执行 mykeymap-settings-server.exe 就能看到错误了
   

 
Terminal只闪了一下就自动关闭了，所以我用screen to gif 在里面找到一帧有字的截出来了，就是有点糊😂
  
我怀疑是 12333 端口被其他程序占用了,  你可以执行按下述步骤排查:
  
Alt + D 激活地址栏并输入 powershell 并回车
 
执行 Get-Process -Id (Get-NetTCPConnection -LocalPort 12333).OwningProcess
  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xianyukang** [comment]
@Mirrorgo 看下是不是其他程序抢占了 12333 端口

**Comment by xianyukang** [comment]
@tmzncty 看起来像被杀毒软件拦截了,  
![image](https://user-images.githubusercontent.com/24707226/140612631-f0453009-fe18-47f3-8f9f-32009132eca5.png)

**Comment by Mirrorgo** [comment]
![image](https://user-images.githubusercontent.com/55936306/140612640-50dac60b-9898-4628-919c-bca1c69620c2.png)

**Comment by tmzncty** [comment]
&nbsp;这就不好说了，我只有win defender，不过手动输入路径，打开设置后解决了问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xianyukang/MyKeymap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月6日(星期六) 晚上10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xianyukang/MyKeymap] 软件无法进入设置界面 (Issue #8)





 
@tmzncty 看起来像被杀毒软件拦截了,
 
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tmzncty** [comment]
好像图片没传上来，我补充一下，方便确认情况。
这一张是手动打开地址后的设置界面。
![图片](https://user-images.githubusercontent.com/72063145/140612792-2cb04616-56ff-4738-8aa6-22f75b728096.png)
这一张是检测端口占用情况。
![图片](https://user-images.githubusercontent.com/72063145/140612792-2cb04616-56ff-4738-8aa6-22f75b728096.png)

**Comment by xianyukang** [comment]
@Mirrorgo @tmzncty 试试下载 1.0.24 版本 ?

**Comment by tmzncty** [comment]
好像图片没传上来，我补充一下。
![图片](https://user-images.githubusercontent.com/72063145/140612843-cd4ccb20-7eb6-47d8-b890-e2a596ae6303.png)
![图片](https://user-images.githubusercontent.com/72063145/140612859-8a24149e-da29-431c-918d-58dea1d124ec.png)

**Comment by tmzncty** [comment]
> 
> 
> @Mirrorgo @tmzncty 试试下载 1.0.24 版本 ?

好的，我现在试试。

**Comment by Mirrorgo** [comment]
![image](https://user-images.githubusercontent.com/55936306/140613019-dd790d3b-3235-4b01-9983-9b37f0c0e3ee.png)

12333应该是没有被占用的。

之前这个“设置界面”我打开过，还正常使用了，自定义了一些功能。但是后来打不开了，删除软件后重新下载了一遍还是没用😭

**Comment by tmzncty** [comment]
问题解决啦，谢谢~
![image](https://user-images.githubusercontent.com/72063145/140613063-66aac7a4-33db-4945-a04b-fa22c2e34ae8.png)
![image](https://user-images.githubusercontent.com/72063145/140613180-62f57db8-a2a0-49c7-8a7d-7309a2ca4c92.png)

**Comment by xianyukang** [comment]
@Mirrorgo 
之前打开过,  后来打不开,  有点奇怪。(0.0)
你截图里下载的版本是 1.0.20,  试试下载 1.0.24 版本?
